### ISSUE TITLE
UnhandledPromiseRejectionWarning when creating new object in the admin interface.

### ISSUE THREAD

**Issue by rgammans** [dkapell/samsara-engine#252]
On a clean instance (but after fixing #251) I see the following error when trying to create a new object.

This happens for gamestates, characters, Transitions, and maybe others too.

```
(node:11353) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at Object.getHistory (/home/roger/sources/samsara-engine/lib/chat.js:239:96)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GameServer.(node:11353) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at Object.getHistory (/home/roger/sources/samsara-engine/lib/chat.js:239:96)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GameServer.handleChatHistory (/home/roger/sources/samsara-engine/lib/GameServer.js:450:30)
    at async GameServer.handleConnection (/home/roger/sources/samsara-engine/lib/GameServer.js:157:9)
    at async WebSocketServer.<anonymous> (/home/roger/sources/samsara-engine/lib/GameServer.js:51:13)
(node:11353) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 248)
handleChatHistory (/home/roger/sources/samsara-engine/lib/GameServer.js:450:30)
    at async GameServer.handleConnection (/home/roger/sources/samsara-engine/lib/GameServer.js:157:9)
    at async WebSocketServer.<anonymous> (/home/roger/sources/samsara-engine/lib/GameServer.js:51:13)
(node:11353) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 248)
```

**Comment by dkapell** [comment]
added `insert into runs (name, current) values ('Initial Run', 'true');` to create an initial, active run, which is what's causing this issue, i'm pretty sure
